source 'https://rubygems.org'

gem 'activesupport', '~> 6.1', require: false
gem 'byebug'
gem 'memory_profiler'
gem 'multipart-post'
gem 'rspec', '~> 3.11'
gem 'rtesseract', '~> 3.1'
gem 'simplecov', require: false, group: :test
