name: ci

on: [ push ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.1
      - run: node --version
      - run: npm install
      - run: ./test.sh
  integration:
    runs-on: ubuntu-latest
    env:
      THUNDERBIRD_VERSION: latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - run: ./script/docker_integration_test.sh
