name: ci

on: [ push ]

jobs:
  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21.1
      - run: node --version
      - run: npm install
      - run: ./test.sh
  integration:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      -
        name: Extended support release
        env:
          THUNDERBIRD_VERSION: esr
        run: ./script/docker_integration_test.sh
      # reusing same job to test different versions, and save some time in docker image
      # building
      -
        name: latest version
        env:
          THUNDERBIRD_VERSION: latest
        run: ./script/docker_integration_test.sh
      -
        name: beta-latest version
        env:
          THUNDERBIRD_VERSION: beta-latest
        run: ./script/docker_integration_test.sh
